#!/usr/bin/env node
// Release helper for Disruptor Proxy.
//
// Bumps the version everywhere it is pinned (package.json, package-lock.json, and
// src-tauri/Cargo.toml + Cargo.lock's own entry), commits that as one release commit, tags it, and
// pushes both. Pushing the tag is the whole handoff - .github/workflows/release.yml picks
// it up from there: builds, signs with the updater keypair, and publishes ONE DRAFT release
// on this repo. This script never builds, signs, or publishes anything itself, and never
// touches GitHub Releases.
//
// Usage:
//   npm run release -- 1.2.0
//   npm run release -- patch | minor | major
//   npm run release -- 1.2.0 --dry-run
//
// After it finishes: review the draft release on GitHub and publish it manually. A draft is
// invisible to the auto-updater and to anonymous downloads until you do that.

import { execFileSync } from 'node:child_process';
import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import path from 'node:path';
import process from 'node:process';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const VERSION_PATTERN = /^\d+\.\d+\.\d+$/;

function fail(message)
{
    console.error('release: ' + message);
    process.exit(1);
}

function log(message)
{
    console.log(message);
}

const dryRun = process.argv.includes('--dry-run');
const noBump = process.argv.includes('--no-bump');

// `file` + an argv array, not one shell string: a value that happens to contain shell
// metacharacters cannot change what command runs, since there is no string for it to break
// out of. NO shell option at all, on any platform: unlike npm/npx, `git` and `cargo` are
// real executables (git.exe, cargo.exe on Windows too - confirmed with `where`), not .cmd
// shims that need a shell interpreter to launch, so execFileSync can spawn them directly.
// That also sidesteps Node's own DEP0190 advisory (`shell: true` + an args array), which
// applies to the .cmd-shim case this script does not have.
function query(file, args)
{
    return execFileSync(file, args, { cwd: ROOT, encoding: 'utf8' }).trim();
}

/** Runs a state-changing command, honouring --dry-run and forwarding stdio. */
function act(file, args, extra)
{
    log('  $ ' + [file, ...args].join(' '));
    if (dryRun)
    {
        return;
    }
    execFileSync(file, args, { cwd: ROOT, stdio: 'inherit', ...(extra ?? {}) });
}

/** Resolves a version input - a full X.Y.Z or a patch/minor/major bump keyword. */
function resolveVersion(input, current)
{
    if (VERSION_PATTERN.test(input))
    {
        return input;
    }
    const parts = current.split('.').map(Number);
    const major = parts[0] ?? 0;
    const minor = parts[1] ?? 0;
    const patch = parts[2] ?? 0;

    if (input === 'patch')
    {
        return `${ major }.${ minor }.${ patch + 1 }`;
    }
    if (input === 'minor')
    {
        return `${ major }.${ minor + 1 }.0`;
    }
    if (input === 'major')
    {
        return `${ major + 1 }.0.0`;
    }
    fail(`"${ input }" is neither a version (X.Y.Z) nor a bump keyword (patch, minor, major)`);
    return ''; // unreachable - fail() exits the process
}

/** Updates package.json + src-tauri/Cargo.toml, then syncs both lockfiles' own entries. */
function bumpVersion(version)
{
    const pkgPath = path.join(ROOT, 'package.json');
    const pkg = JSON.parse(readFileSync(pkgPath, 'utf8'));

    pkg.version = version;
    if (!dryRun)
    {
        writeFileSync(pkgPath, JSON.stringify(pkg, null, 4) + '\n');
    }
    log(`  package.json -> ${ version }`);

    // package-lock.json records the root package's version in two places. Patch those two
    // fields in place rather than shelling out to `npm install --package-lock-only`: that
    // re-resolves the whole dependency tree, and a lockfile regenerated by a different npm
    // than CI runs has already broken every job here once. Reuse the file's own indent so
    // the bump stays a two-line diff instead of reformatting 2800 lines.
    const lockPath = path.join(ROOT, 'package-lock.json');
    if (existsSync(lockPath))
    {
        const raw = readFileSync(lockPath, 'utf8');
        const indent = raw.match(/^\s*\{\s*?\n([ \t]+)/)?.[1] ?? '  ';
        const lock = JSON.parse(raw);

        lock.version = version;
        if (lock.packages?.[''])
        {
            lock.packages[''].version = version;
        }
        if (!dryRun)
        {
            writeFileSync(lockPath, JSON.stringify(lock, null, indent) + '\n');
        }
        log(`  package-lock.json -> ${ version }`);
    }

    const cargoPath = path.join(ROOT, 'src-tauri', 'Cargo.toml');
    const cargoText = readFileSync(cargoPath, 'utf8');
    const cargoNext = cargoText.replace(/^version = "[^"]*"/m, `version = "${ version }"`);

    if (cargoNext === cargoText)
    {
        fail('src-tauri/Cargo.toml: no `version = "..."` line found under [package] - bump it by hand');
    }
    if (!dryRun)
    {
        writeFileSync(cargoPath, cargoNext);
    }
    log(`  src-tauri/Cargo.toml -> ${ version }`);

    // Cargo.lock pins this package's OWN version too; `cargo check` reconciles just that
    // entry against the Cargo.toml bump above without re-resolving unrelated dependencies,
    // so committing the lockfile alongside the bump doesn't surprise the next `cargo build`.
    if (!dryRun && existsSync(path.join(ROOT, 'src-tauri', 'Cargo.lock')))
    {
        act('cargo', ['check', '--quiet'], { cwd: path.join(ROOT, 'src-tauri') });
    }
}

function printHelp()
{
    log(`Release Disruptor Proxy.

Usage:  npm run release -- <version | patch | minor | major> [options]
        node scripts/release.mjs <version | patch | minor | major> [options]

Bumps package.json + src-tauri/Cargo.toml (+ syncs both lockfiles' own
entries), commits, tags, and pushes. Pushing the tag is the whole handoff -
.github/workflows/release.yml takes it from there: builds, signs, and
publishes one DRAFT release on this repo.

Examples:
  npm run release -- 1.2.0
  npm run release -- patch
  npm run release -- minor --dry-run
  npm run release -- --no-bump

Options:
  --no-bump    Don't bump/commit/tag; just push the existing v<current> tag,
               re-triggering the release workflow for the version already set.
  --dry-run    Show every step; change nothing.
  -h, --help   Show this help.`);
}

const argvRaw = process.argv.slice(2);

if (argvRaw.includes('-h') || argvRaw.includes('--help'))
{
    printHelp();
    process.exit(0);
}

const argv = argvRaw.filter(a => a !== '--dry-run' && a !== '--no-bump');
const versionArg = argv[0];

if (versionArg !== undefined && versionArg.startsWith('-'))
{
    fail(`unknown option: ${ versionArg } (try --help)`);
}

const pkgPath = path.join(ROOT, 'package.json');
const current = JSON.parse(readFileSync(pkgPath, 'utf8')).version;

let released;
let tag;

if (noBump)
{
    // Re-trigger a release for the version already in package.json: no bump, no commit,
    // no new tag - just push the existing tag (and HEAD). For when a prior run tagged but
    // the push or the CI run didn't land.
    released = current;
    tag = 'v' + current;

    log(`\nRe-releasing ${ current }  (tag ${ tag }, no bump)`);
    if (dryRun)
    {
        log('  (dry run: nothing will be pushed)');
    }

    if (query('git', ['tag', '-l', tag]) !== tag)
    {
        fail(`tag ${ tag } does not exist locally - run without --no-bump to create it first`);
    }
}
else
{
    if (!versionArg)
    {
        fail('a version or bump keyword is required, e.g. `npm run release -- patch` or `-- 1.2.0` (try --help)');
    }

    released = resolveVersion(versionArg, current);

    if (!VERSION_PATTERN.test(released))
    {
        fail(`"${ released }" is not a valid version (expected MAJOR.MINOR.PATCH)`);
    }

    tag = 'v' + released;

    log(`\nRelease ${ current } -> ${ released }  (tag ${ tag })`);
    if (dryRun)
    {
        log('  (dry run: nothing will be changed)');
    }

    const status = query('git', ['status', '--porcelain']);
    if (status && !dryRun)
    {
        fail('working tree is not clean; commit or stash first - the release commit must be just the version bump');
    }

    if (query('git', ['tag', '-l', tag]) === tag)
    {
        fail(`tag ${ tag } already exists`);
    }

    log('\nBumping version');
    bumpVersion(released);

    log('\nCommitting and tagging');
    act('git', ['add', 'package.json', 'package-lock.json', 'src-tauri/Cargo.toml', 'src-tauri/Cargo.lock']);
    act('git', ['commit', '-m', `chore(release): ${ tag }`]);
    act('git', ['tag', '-a', tag, '-m', tag]);
}

log('\nPushing to GitHub');
act('git', ['push', 'origin', 'HEAD']);
act('git', ['push', 'origin', tag]);

log(`\nDone: ${ released }`);
log('CI is now building, signing, and publishing a draft release on this repo.');
log('Review the draft on GitHub, then publish it manually when ready - a draft is');
log('invisible to the updater and to anonymous downloads until you do.');
